"use client";

import { FormEvent, useEffect, useRef, useState } from "react";

export type AdminSessionLogDraft = { what_went_well: string; challenges: string; recovery_notes: string; homework: string; additional_notes: string; outcome: "strong" | "improving" | "needs_work" | "regression_concern" };
type StoredDraft = { dogId: string; sessionId: string; updatedAt: number; values: AdminSessionLogDraft };
type Props = { dogId: string; session: { id: string; session_number: number }; saving: boolean; onCancel: () => void; onSubmit: (values: AdminSessionLogDraft) => Promise<void> };
const maxDraftAge = 7 * 24 * 60 * 60 * 1000;
const blankDraft = (): AdminSessionLogDraft => ({ what_went_well: "", challenges: "", recovery_notes: "", homework: "", additional_notes: "", outcome: "improving" });
export const adminSessionDraftKey = (dogId: string, sessionId: string) => `patriot-k9-admin-session-draft:${dogId}:${sessionId}`;

export function hasAdminSessionDraft(dogId: string, sessionId: string) {
  if (typeof window === "undefined") return false;
  try { const raw = window.localStorage.getItem(adminSessionDraftKey(dogId, sessionId)); if (!raw) return false; const stored = JSON.parse(raw) as StoredDraft; if (stored.dogId !== dogId || stored.sessionId !== sessionId || Date.now() - stored.updatedAt > maxDraftAge) { window.localStorage.removeItem(adminSessionDraftKey(dogId, sessionId)); return false; } return true; } catch { return false; }
}

export default function AdminSessionCompletionForm({ dogId, session, saving, onCancel, onSubmit }: Props) {
  const key = adminSessionDraftKey(dogId, session.id); const [values, setValues] = useState<AdminSessionLogDraft>(blankDraft); const [restored, setRestored] = useState(false); const [draftStatus, setDraftStatus] = useState<"idle" | "saving" | "saved">("idle"); const dirty = useRef(false);
  useEffect(() => { try { const raw = window.localStorage.getItem(key); if (!raw) return; const stored = JSON.parse(raw) as StoredDraft; if (stored.dogId !== dogId || stored.sessionId !== session.id || Date.now() - stored.updatedAt > maxDraftAge) { window.localStorage.removeItem(key); return; } setValues({ ...blankDraft(), ...stored.values }); setRestored(true); dirty.current = true; } catch { window.localStorage.removeItem(key); } }, [dogId, key, session.id]);
  useEffect(() => { if (!dirty.current) return; setDraftStatus("saving"); const timeout = window.setTimeout(() => { try { window.localStorage.setItem(key, JSON.stringify({ dogId, sessionId: session.id, updatedAt: Date.now(), values } satisfies StoredDraft)); setDraftStatus("saved"); } catch { setDraftStatus("idle"); } }, 500); return () => window.clearTimeout(timeout); }, [dogId, key, session.id, values]);
  useEffect(() => { const protect = (event: BeforeUnloadEvent) => { if (!dirty.current) return; event.preventDefault(); event.returnValue = "You have an unfinished session log."; }; const persist = () => { if (!dirty.current) return; try { window.localStorage.setItem(key, JSON.stringify({ dogId, sessionId: session.id, updatedAt: Date.now(), values } satisfies StoredDraft)); } catch { /* Storage may be unavailable. */ } }; window.addEventListener("beforeunload", protect); window.addEventListener("pagehide", persist); return () => { window.removeEventListener("beforeunload", protect); window.removeEventListener("pagehide", persist); }; }, [dogId, key, session.id, values]);
  const update = (field: keyof AdminSessionLogDraft, value: string) => { dirty.current = true; setValues((current) => ({ ...current, [field]: value })); };
  const discard = () => { if (!window.confirm("Discard this unfinished session log? This cannot be undone.")) return; window.localStorage.removeItem(key); dirty.current = false; setValues(blankDraft()); setRestored(false); setDraftStatus("idle"); };
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); try { await onSubmit(values); window.localStorage.removeItem(key); dirty.current = false; } catch { /* The parent surfaces the save error; retain this local draft. */ } };
  return <div className="fixed inset-0 z-[60] overflow-y-auto bg-black/70 p-4"><form onSubmit={(event) => void submit(event)} className="mx-auto my-4 w-full max-w-xl rounded-2xl border border-amber-400/25 bg-neutral-950 p-6 shadow-[0_24px_70px_rgba(0,0,0,0.6)]"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-amber-300">Complete Session {session.session_number}</p><h2 className="mt-2 text-2xl font-bold text-white">Log training results</h2></div><div className="text-right text-xs text-neutral-400" role="status">{restored ? <p className="text-emerald-200">Draft restored</p> : null}<p>{draftStatus === "saving" ? "Saving draft..." : draftStatus === "saved" ? "Draft saved" : ""}</p></div></div><div className="mt-5 space-y-3">{([ ["what_went_well", "What went well?"], ["challenges", "Challenges"], ["recovery_notes", "Recovery / Stability"], ["homework", "Homework"], ["additional_notes", "Additional Trainer Notes"] ] as Array<[keyof AdminSessionLogDraft, string]>).map(([name, label]) => <label key={name} className="block text-sm font-semibold text-neutral-200">{label}<textarea value={values[name] as string} onChange={(event) => update(name, event.target.value)} rows={3} className="mt-2 w-full rounded-lg border border-neutral-700 bg-black/40 px-3 py-2.5 text-white" /></label>)}<label className="block text-sm font-semibold text-neutral-200">Outcome<select value={values.outcome} onChange={(event) => update("outcome", event.target.value)} className="mt-2 min-h-11 w-full rounded-lg border border-neutral-700 bg-black/40 px-3 py-2.5 text-white"><option value="strong">Strong</option><option value="improving">Improving</option><option value="needs_work">Needs Work</option><option value="regression_concern">Regression / Concern</option></select></label></div><div className="mt-6 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button type="button" onClick={discard} disabled={saving} className="min-h-11 rounded-lg border border-red-400/35 px-4 py-2.5 text-sm font-bold text-red-200">Discard Draft</button><button type="button" onClick={onCancel} disabled={saving} className="min-h-11 rounded-lg border border-neutral-700 px-4 py-2.5 text-sm font-bold text-neutral-200">Cancel</button><button type="submit" disabled={saving} className="min-h-11 rounded-lg bg-amber-400 px-4 py-2.5 text-sm font-bold text-black disabled:opacity-60">{saving ? "Completing..." : "Complete Session"}</button></div></form></div>;
}
