"use client";

import { useState } from "react";

export default function DeleteLitterButton({ litterId, label, onDeleted }: { litterId: string; label: string; onDeleted: () => void }) {
  const [open, setOpen] = useState(false); const [deleting, setDeleting] = useState(false); const [error, setError] = useState("");
  const remove = async () => { setDeleting(true); setError(""); try { const response = await fetch(`/api/admin/litters/${encodeURIComponent(litterId)}`, { method: "DELETE" }); const data = await response.json() as { success?: boolean; error?: string }; if (!response.ok || !data.success) throw new Error(data.error || "Unable to delete litter."); setOpen(false); onDeleted(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to delete litter."); } finally { setDeleting(false); } };
  return <><button type="button" onClick={() => setOpen(true)} className="rounded-lg border border-red-500/40 px-3 py-2 text-sm font-semibold text-red-200 hover:bg-red-500/10">{label}</button>{open && <div className="fixed inset-0 z-[80] flex items-end bg-black/70 p-4 sm:items-center sm:justify-center"><div role="dialog" aria-modal="true" aria-labelledby="delete-litter-title" className="w-full max-w-md rounded-2xl border border-red-500/30 bg-neutral-950 p-6 shadow-2xl"><h2 id="delete-litter-title" className="text-2xl font-bold text-white">Delete this litter?</h2><p className="mt-3 text-sm leading-6 text-neutral-300">This will permanently remove this litter and all puppy records and internal data associated with it. This action cannot be undone.</p>{error && <p className="mt-4 text-sm text-red-200" role="alert">{error}</p>}<div className="mt-6 flex justify-end gap-3"><button type="button" disabled={deleting} onClick={() => setOpen(false)} className="rounded-lg border border-neutral-700 px-4 py-2 text-neutral-200">Cancel</button><button type="button" disabled={deleting} onClick={() => void remove()} className="rounded-lg bg-red-500 px-4 py-2 font-bold text-white disabled:opacity-60">{deleting ? "Deleting..." : "Delete Litter"}</button></div></div></div>}</>;
}
